### ISSUE TITLE
mod causes world crash sometimes

### ISSUE THREAD

**Issue by art0007i** [XDelta/ResoniteDirectEditGlobal#1]
to reproduce: 
1. create a new world
2. spawn some item with a lot of protoflux (in my case I used this one `resdb:///da7cab0e297f689fa287bab71385f4e529ac3e94ac7c4720d4581fc0f7c8c2c7.brson`)
1. spawn this item: `resdb:///5b26f51c9fa0f8be8a88484d0ce86d12a110757ec6340de165cea332720107a1.brson`
3. equip it and click primary

it will crash the world.

here's a stack trace + some stuff the mod outputs before crashing the world
[relevant_log.txt](https://github.com/XDelta/ResoniteDirectEditGlobal/files/13502793/relevant_log.txt)

**Comment by XDelta** [comment]
The features of this mod have been implemented officially as of 2023.11.13.1343, Using the mod still is probably not needed. https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/303

I am atleast not aware of any case where it provides the functionality where the game doesn't do so now

**Comment by art0007i** [comment]
oh ok, then you should put a note in the readme that this mod is no longer necessary and potentially archive it too
